# Generated by Django 5.2.8 on 2025-11-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_taskmodel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskmodel',
            name='description',
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High')], default='normal', max_length=10),
        ),
    ]
